import Head from "next/head";
import Image from "next/image";
import BookList from "../components/BookList";
import AddBook from "../components/AddBook";
import { ApolloClient, InMemoryCache, ApolloProvider } from "@apollo/client";
//configuracion apollo client
const client = new ApolloClient({
  uri: "http://localhost:8000/graphql",
  cache: new InMemoryCache(),
});

export default function Home() {
  return (
    <div>
      <Head>
        <title>Ninja's Reading List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;700&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main>
        <ApolloProvider client={client}>
          <div id="main">
            <h1>Ninja's Reading List</h1>
            <BookList />
            <AddBook />
          </div>
        </ApolloProvider>
      </main>
    </div>
  );
}
